config/routes.rb
Rails.application.routes.draw do
  resources :meal_plans
  resources :taggings
  resources :user_tags
  resources :recipes

  get '/account', to: 'pages#account', as: :current_user
  resources :users

  get '/sessions/new', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions/:id', to: 'sessions#destroy'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :meal_plan
  has_many :user_tags
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :recipe
  belongs_to :user_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :meal_plans
  has_many :recipes
  has_many :user_tags

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, on: :create, presence: true, length: { minimum: 8 }
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  has_many :recipes
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def account
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/account'
    else
      @errors = user.errors.full_messages
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
end

app/controllers/user_tags_controller.rb
class UserTagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new
    user.first_name = params[:first_name]
    user.last_name = params[:last_name]
    user.email = params[:email]
    user.password = params[:password]
    confirm_password = params[:confirm_password]
    if user.password == confirm_password
      user.save
      redirect_to '/account'
    else
      @errors = user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/user_tags_helper.rb
module UserTagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Recipe Hoarder</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="nav-extended">
        <div class="nav-wrapper">
          <%= link_to 'Recipe Hoarder', root_path, class: 'brand-logo' %>
          <ul id="nav-mobile" class="right hand-on-med-and-down">
            <% if logged_in? %>
              <li>Hello <%= current_user.first_name %></li>
              <li>
                <%= form_tag("/sessions/#{current_user.id}", method: :delete) do %>
                  <%= button_tag 'Log Out', type: 'submit', class: "btn waves-effect waves-light" %>
                <% end %>
              </li>
            <% else %>
              <%= link_to 'Log In', '/sessions/new' %>
            <% end %>
          </ul>
        </div>
        <div class="nav-content">
          <ul class="tabs tabs-transparent">
            <li class="tab"><%= link_to 'Recipes', new_recipe_path %></li>
            <li class="tab"><%= link_to 'Meal Planner', meal_plans_path %></li>
          </ul>
        </div>
      </nav>

    </header>

    <%= yield %>
    
  </body>
</html>

app/views/pages/account.html.erb
<%= current_user.first_name %>
<%= current_user.last_name %>
<%= current_user.email %>

app/views/pages/index.html.erb
<h1>All your recipes in 1 place</h1>
<%= image_tag('logo.jpg') %>